#!/bin/bash
# Automatically check jw.org inbox for new messages
# In popular Linux distros (e.g. Ubuntu) all of the programs here come pre-installed. (Except maybe your favorite browser.) 
# These may include: wget, notify-send, gpg, mplayer|aplay, firefox|google-chrome|?
# You may check stderr if one of those programs aren't installed
# v3

# Check for multiple sessions of script
[[ "`ps -e | grep -c $(basename $0)`" -gt "2" ]] && echo -e "`basename $0`: Mutiple instances found. Terminating this process." && exit 1

# Change to current directory of the script (optional)
cd "`dirname $0`"

# jw.org account details
# (Option 1 - plaintext passwords)
username=''
password=''

# Authentication (modification optional, see below)
auth="txtUserName=$username&txtPassword=$password"

# (Option 2 - encrypted username and password)
# If you prefer a password in an encrypted file, encrypt username and password in this format:
# txtUserName=$username&txtPassword=$password
# i.e. `echo "txtUserName=$username&txtPassword=$password" | gpg -c - > .encrypted-file`
# You may wish to store this file separated from the script directory and do a `chmod 600`
# Store auth as below:

# auth=`gpg --batch -q --no-use-agent --passphrase-file /path/to/passphrase -d ./encrypted-file`

# Optional. Domain code - only for those with multiple domains. Leave blank for those with single domains.
# This is the unique numeric/alphanumeric code for your domain.
# First login to your account in a browser and see the URL in the format: https://www.jw.org/apps/<LANG>_<txtAcct>_<PAGE>
# For example, you may see in the address bar immediately after you logged in: https://www.jw.org/apps/E_1234567890_ADMIN
# Then your txtAcct would be: 1234567890
txtAcct=''

# Add an underscore to txtAcct if present
[ ! -z "$txtAcct" ] && txtAcct=_$txtAcct

# Time interval when checking jw.org account, could be: second, minute, hour, day: s m h d
checkevery=3h

# For sound notifications
# I personally use "aplay -q" since my sound is wav, i.e. "/usr/share/sounds/Feather Sound Set/incoming_call.wav"
player="mplayer"
sound="/path/to/sound"

# Browser to use, e.g. firefox
browser="google-chrome"

# URL transforms
login="https://www.jw.org/apps/E_LOGIN1"
post="https://www.jw.org/apps/E_LOGIN2"
logout="https://www.jw.org/apps/E$((txtAcct))_LOGOUT"

inbox="https://www.jw.org/apps/E$((txtAcct))_INBOX"
changed="https://www.jw.org/apps/E$((txtAcct))_NOTIFICATIONS?txtAction=CHANGEDWIKIDOCS"
letters="https://www.jw.org/apps/E$((txtAcct))_VIEWLETTER"
forms="https://www.jw.org/apps/E$((txtAcct))_VIEWFORM"
media="https://www.jw.org/apps/E$((txtAcct))_VIEWEVENTMEDIA"

# Main script

while true; do
	while true; do
		# maj-online && break # May optionally use my online connectivity checker
		nm-online && break
		sleep 1h
	done

wget --post-data """$auth""" --keep-session-cookies --save-cookies .a -qO /dev/null "$post"
	wget --load-cookies ./.a -qO .i "$inbox"
	wget --load-cookies ./.a -qO .c "$changed"
	wget --load-cookies ./.a -qO .l "$letters"
	wget --load-cookies ./.a -qO .f "$forms"
	wget --load-cookies ./.a -qO .m "$media"
	wget --load-cookies ./.a -qO /dev/null "$logout" &

	unread=`cat ./.i | grep -o "Inbox ([0-9]*)" | sed 's/[^0-9]*//g'`

	lettersCount=`cat ./.c | grep -o 'Letters[^}]*' | sed 's/[^0-9]*//g'`
	mediaCount=`cat ./.c | grep -o 'Event Media[^}]*' | sed 's/[^0-9]*//g'`
	formsCount=`cat ./.c | grep -o 'Forms[^}]*' | sed 's/[^0-9]*//g'`
	newsl=`cat ./.c | grep -o 'Sign Language[^}]*' | sed 's/[^0-9]*//g'`

	[[ $lettersCount -gt 0 ]] && lettersContent="`cat ./.l | tr -s ' ' | tr -d '\n' | sed -e 's/docHangIndent/\n/g' | grep -oP "imgToggleDocAbstract.*?<" | grep -o ">.*<" | tr -d '<>' | sed 's/^ //'`"
	[[ $formsCount -gt 0 ]] && formsContent="`cat ./.f | tr -s ' ' | tr -d '\n' | sed -e 's/docHangIndent/\n/g' | grep -oP "imgToggleDocAbstract.*?<" | grep -o ">.*<" | tr -d '<>' | sed 's/^ //'`"
	[[ $mediaCount -gt 0 ]] && mediaContent="`cat ./.m | tr -s ' ' | tr -d '\n' | sed -e 's/docHangIndent/\n/g' | grep -oP "imgToggleDocAbstract.*?<" | grep -o ">.*<" | tr -d '<>' | sed 's/^ //'`"	
	
	shred -fuz .a .i .c .l .f .m
	
	[[ $unread -eq 1 ]] && notify-send -u normal "You have a new message in your jw.org inbox."
	[[ $unread -gt 1 ]] && notify-send -u normal "You have ($unread) new messages in your jw.org inbox."
	[[ $unread -gt 0 ]] && for a in 1 2 3; do $player $sound &>/dev/null; done &
	[[ $unread -gt 0 ]] && $browser $login &>/dev/null &

	[[ $lettersCount -gt 0 ]] && notify-send -u normal "New letters ($lettersCount):" "$lettersContent"
	[[ $lettersCount -gt 0 ]] && for a in 1 2; do $player $sound &>/dev/null; done

	[[ $mediaCount -gt 0 ]] && notify-send -u normal "New media ($mediaCount):" "$mediaContent"
	[[ $mediaCount -gt 0 ]] && for a in 1; do $player $sound &>/dev/null; done

	[[ $formsCount -gt 0 ]] && notify-send -u normal "New forms ($formsCount):" "$formsContent"
	[[ $formsCount -gt 0 ]] && for a in 1; do $player $sound &>/dev/null; done
	
	[[ $newsl -eq 1 ]] && notify-send -u low "There is a new Sign Language document in jw.org."
	[[ $newsl -gt 1 ]] && notify-send -u low "There are ($newsl) new Sign Language documents in jw.org."
	[[ $newsl -gt 0 ]] && $player $sound &>/dev/null

	sleep "$checkevery"
done
