#!/bin/bash

[ -z "$1" ] && { echo "Please enter arch..."; exit 1; }

arch="$1"
ver="7.1"
variant="stock"

tmpname=`cat /dev/urandom | tr -dc 'a-zA-Z' | fold -w 8 | head -n 1`
wget -O "/tmp/$tmpname" "https://github.com/opengapps/$arch/releases/latest" || { echo "Download error!"; exit 1; }

dl=`cat /tmp/$tmpname | grep -Po "/.*open_gapps-$arch-$ver-$variant-.*.zip" | sort -u`
[ -z "$dl" ] && { echo "Nothing to download..."; exit 1; }

wget -o /dev/null -b "https://github.com$dl.md5"
aria2c -x10 -m0 -k1M "https://github.com$dl"

ls
